# Generated by Django 5.0.1 on 2026-05-31 07:20

import django.contrib.gis.db.models.fields
import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GBVService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.CharField(max_length=100, verbose_name="state")),
                (
                    "lga",
                    models.CharField(blank=True, max_length=100, verbose_name="LGA"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "organisation_type",
                    models.CharField(
                        choices=[
                            ("governmental", "Governmental"),
                            ("national_ngo", "National NGO"),
                            ("international_ngo", "International NGO"),
                            ("private", "Private"),
                            ("other", "Other"),
                        ],
                        default="governmental",
                        max_length=50,
                        verbose_name="organisation type",
                    ),
                ),
                (
                    "services",
                    models.TextField(blank=True, verbose_name="services offered"),
                ),
                (
                    "target_group",
                    models.CharField(
                        choices=[
                            ("adults_and_children", "Adults and Children"),
                            ("adults_only", "Adults Only (18 and Over)"),
                            ("children_only", "Children Only (Under 18)"),
                        ],
                        default="adults_and_children",
                        max_length=50,
                        verbose_name="target group",
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="address")),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="phone number"
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="contact person"
                    ),
                ),
                (
                    "accessibility_info",
                    models.TextField(blank=True, verbose_name="accessibility info"),
                ),
                (
                    "operating_hours",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="operating hours"
                    ),
                ),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326, verbose_name="location"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "GBV service",
                "verbose_name_plural": "GBV services",
                "ordering": ["state", "name"],
                "indexes": [
                    models.Index(fields=["state"], name="gbv_gbvserv_state_2b8040_idx"),
                    models.Index(fields=["lga"], name="gbv_gbvserv_lga_d25b85_idx"),
                    models.Index(
                        fields=["organisation_type"],
                        name="gbv_gbvserv_organis_4b58f3_idx",
                    ),
                    models.Index(
                        fields=["is_active"], name="gbv_gbvserv_is_acti_22541e_idx"
                    ),
                    django.contrib.postgres.indexes.GistIndex(
                        fields=["location"], name="gbv_gbvserv_locatio_a33f93_gist"
                    ),
                ],
            },
        ),
    ]
