# Generated by Django 5.0.1 on 2026-06-09 05:51

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_first_name_alter_user_last_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=apps.users.models.User.get_avatars_storage,
                upload_to="",
                verbose_name="profile picture",
            ),
        ),
    ]
