# Generated by Django 5.1.15 on 2026-07-31 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="otp_code",
            field=models.CharField(
                blank=True, max_length=6, null=True, verbose_name="otp code"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="otp_created_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="otp created at"
            ),
        ),
    ]
