# Generated by Django 5.0.1 on 2026-09-08 10:42

import apps.users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_otp_code_user_otp_created_at"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", apps.users.models.CaseInsensitiveUserManager()),
            ],
        ),
    ]
