# Generated by Django 5.0.1 on 2026-04-09 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="comment",
        ),
        migrations.RemoveField(
            model_name="review",
            name="title",
        ),
        migrations.AddField(
            model_name="review",
            name="body",
            field=models.TextField(blank=True, default="", verbose_name="review text"),
        ),
        migrations.AddField(
            model_name="review",
            name="flag_count",
            field=models.PositiveIntegerField(default=0, verbose_name="flag count"),
        ),
        migrations.AddField(
            model_name="review",
            name="is_anonymous",
            field=models.BooleanField(default=False, verbose_name="anonymous"),
        ),
        migrations.AddField(
            model_name="review",
            name="is_published",
            field=models.BooleanField(default=True, verbose_name="published"),
        ),
    ]
