# Generated by Django 5.0.1 on 2026-04-13 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0003_remove_review_comment_remove_review_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="body",
            field=models.TextField(verbose_name="review text"),
        ),
    ]
