# Generated by Django 5.0.1 on 2026-07-02 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0004_alter_review_body"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="review",
            unique_together=set(),
        ),
    ]
