# Generated by Django 5.0.1 on 2026-03-23 15:34

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Facility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="facility name"
                    ),
                ),
                (
                    "facility_type",
                    models.CharField(
                        choices=[
                            ("hospital", "Hospital"),
                            ("clinic", "Clinic"),
                            ("pharmacy", "Pharmacy"),
                            ("laboratory", "Laboratory"),
                            ("diagnostic", "Diagnostic Center"),
                            ("maternity", "Maternity Home"),
                            ("dental", "Dental Clinic"),
                            ("eye", "Eye Clinic"),
                            ("physiotherapy", "Physiotherapy Center"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="facility type",
                    ),
                ),
                ("address", models.TextField(verbose_name="address")),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        geography=True,
                        help_text="Geospatial coordinates (longitude, latitude)",
                        srid=4326,
                        verbose_name="location",
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="city"),
                ),
                (
                    "state",
                    models.CharField(blank=True, max_length=100, verbose_name="state"),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="phone number"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="email"),
                ),
                ("website", models.URLField(blank=True, verbose_name="website")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "services",
                    models.TextField(
                        blank=True,
                        help_text="Comma-separated list of services",
                        verbose_name="services offered",
                    ),
                ),
                (
                    "monday_hours",
                    models.CharField(
                        blank=True,
                        default="9:00 AM - 5:00 PM",
                        max_length=50,
                        verbose_name="Monday hours",
                    ),
                ),
                (
                    "tuesday_hours",
                    models.CharField(
                        blank=True,
                        default="9:00 AM - 5:00 PM",
                        max_length=50,
                        verbose_name="Tuesday hours",
                    ),
                ),
                (
                    "wednesday_hours",
                    models.CharField(
                        blank=True,
                        default="9:00 AM - 5:00 PM",
                        max_length=50,
                        verbose_name="Wednesday hours",
                    ),
                ),
                (
                    "thursday_hours",
                    models.CharField(
                        blank=True,
                        default="9:00 AM - 5:00 PM",
                        max_length=50,
                        verbose_name="Thursday hours",
                    ),
                ),
                (
                    "friday_hours",
                    models.CharField(
                        blank=True,
                        default="9:00 AM - 5:00 PM",
                        max_length=50,
                        verbose_name="Friday hours",
                    ),
                ),
                (
                    "saturday_hours",
                    models.CharField(
                        blank=True,
                        default="Closed",
                        max_length=50,
                        verbose_name="Saturday hours",
                    ),
                ),
                (
                    "sunday_hours",
                    models.CharField(
                        blank=True,
                        default="Closed",
                        max_length=50,
                        verbose_name="Sunday hours",
                    ),
                ),
                (
                    "has_parking",
                    models.BooleanField(default=False, verbose_name="has parking"),
                ),
                (
                    "has_wheelchair_access",
                    models.BooleanField(
                        default=False, verbose_name="wheelchair accessible"
                    ),
                ),
                (
                    "has_emergency_service",
                    models.BooleanField(
                        default=False, verbose_name="has emergency service"
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Has this facility been verified by admin?",
                        verbose_name="verified",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Is this facility currently operational?",
                        verbose_name="active",
                    ),
                ),
                (
                    "average_rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="average rating",
                    ),
                ),
                (
                    "total_reviews",
                    models.IntegerField(default=0, verbose_name="total reviews"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "verbose_name": "facility",
                "verbose_name_plural": "facilities",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["name"], name="facilities__name_412513_idx"),
                    models.Index(
                        fields=["facility_type"], name="facilities__facilit_dd5426_idx"
                    ),
                    models.Index(
                        fields=["is_verified", "is_active"],
                        name="facilities__is_veri_1f1965_idx",
                    ),
                    models.Index(
                        fields=["average_rating"], name="facilities__average_fc0e1b_idx"
                    ),
                    models.Index(
                        fields=["location"], name="facilities__locatio_b28cee_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="FacilityImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="facilities/%Y/%m/%d/", verbose_name="image"
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="caption"
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Is this the main image for the facility?",
                        verbose_name="primary image",
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="uploaded at"),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="facilities.facility",
                    ),
                ),
            ],
            options={
                "verbose_name": "facility image",
                "verbose_name_plural": "facility images",
                "ordering": ["-is_primary", "-uploaded_at"],
            },
        ),
    ]
