# Generated by Django 5.0.1 on 2026-04-09 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="facility",
            name="lga",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=100,
                verbose_name="local government area",
            ),
        ),
        migrations.AddField(
            model_name="facility",
            name="operating_hours",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Structured weekly schedule",
                verbose_name="operating hours",
            ),
        ),
    ]
