# Generated by Django 5.0.1 on 2026-04-09 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0002_facility_lga_facility_operating_hours"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facility",
            name="facility_type",
            field=models.CharField(
                choices=[
                    ("hospital", "Hospital"),
                    ("clinic", "Clinic"),
                    ("pharmacy", "Pharmacy"),
                    ("laboratory", "Laboratory"),
                    ("diagnostic", "Diagnostic Center"),
                    ("maternity", "Maternity Home"),
                    ("dental", "Dental Clinic"),
                    ("eye", "Eye Clinic"),
                    ("physiotherapy", "Physiotherapy Center"),
                    ("other", "Other"),
                ],
                db_index=True,
                max_length=50,
                verbose_name="facility type",
            ),
        ),
    ]
