# Generated by Django 5.0.1 on 2026-04-19 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0003_alter_facility_facility_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="facility",
            name="care_level",
            field=models.CharField(
                choices=[
                    ("primary", "Primary"),
                    ("secondary", "Secondary"),
                    ("tertiary", "Tertiary"),
                    ("other", "Other"),
                ],
                db_index=True,
                default="primary",
                max_length=20,
                verbose_name="care level",
            ),
        ),
        migrations.AddField(
            model_name="facility",
            name="ownership",
            field=models.CharField(
                choices=[
                    ("federal_government", "Federal Government"),
                    ("state_government", "State Government"),
                    ("lga", "Local Government (LGA)"),
                    ("private", "Private"),
                    ("mission", "Mission/Faith-based"),
                    ("ngo", "NGO"),
                    ("other", "Other"),
                ],
                db_index=True,
                default="private",
                max_length=50,
                verbose_name="ownership type",
            ),
        ),
    ]
