# Generated by Django 5.0.1 on 2026-04-27 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0004_facility_care_level_facility_ownership"),
    ]

    operations = [
        migrations.AddField(
            model_name="facility",
            name="has_sarcs",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Does this facility have a Sexual Assault Referral Centre unit?",
                verbose_name="has SARC",
            ),
        ),
        migrations.CreateModel(
            name="SARCProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unit_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of the SARC unit e.g. Hope Centre",
                        max_length=255,
                        verbose_name="SARC unit name",
                    ),
                ),
                (
                    "hotline_number",
                    models.CharField(
                        blank=True,
                        help_text="24/7 crisis hotline number",
                        max_length=20,
                        verbose_name="hotline number",
                    ),
                ),
                (
                    "is_24_hours",
                    models.BooleanField(default=False, verbose_name="24 hour service"),
                ),
                (
                    "accepts_walk_ins",
                    models.BooleanField(default=True, verbose_name="accepts walk-ins"),
                ),
                (
                    "confidentiality_assured",
                    models.BooleanField(
                        default=True, verbose_name="confidentiality assured"
                    ),
                ),
                (
                    "has_police_presence",
                    models.BooleanField(
                        default=False, verbose_name="has police presence"
                    ),
                ),
                (
                    "has_legal_aid",
                    models.BooleanField(default=False, verbose_name="has legal aid"),
                ),
                (
                    "has_counseling",
                    models.BooleanField(default=False, verbose_name="has counseling"),
                ),
                (
                    "has_hiv_pep",
                    models.BooleanField(default=False, verbose_name="has HIV PEP"),
                ),
                (
                    "has_emergency_contraception",
                    models.BooleanField(
                        default=False, verbose_name="has emergency contraception"
                    ),
                ),
                (
                    "has_shelter_referral",
                    models.BooleanField(
                        default=False, verbose_name="has shelter referral"
                    ),
                ),
                (
                    "has_forensic",
                    models.BooleanField(
                        default=False, verbose_name="has forensic examination"
                    ),
                ),
                (
                    "has_sti_testing",
                    models.BooleanField(default=False, verbose_name="has STI testing"),
                ),
                (
                    "has_court_support",
                    models.BooleanField(
                        default=False, verbose_name="has court support"
                    ),
                ),
                (
                    "languages",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='List of languages spoken e.g. ["English", "Yoruba"]',
                        verbose_name="languages supported",
                    ),
                ),
                (
                    "additional_info",
                    models.TextField(blank=True, verbose_name="additional information"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "facility",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sarc_profile",
                        to="facilities.facility",
                    ),
                ),
            ],
            options={
                "verbose_name": "SARC profile",
                "verbose_name_plural": "SARC profiles",
            },
        ),
    ]
