# Generated by Django 5.0.1 on 2026-04-29 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0005_facility_has_sarcs_sarcprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="facility",
            name="has_fistula_programme",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Is free fistula surgery available at this facility?",
                verbose_name="has fistula programme",
            ),
        ),
    ]
