# Generated by Django 5.0.1 on 2026-06-07 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0006_facility_has_fistula_programme"),
    ]

    operations = [
        migrations.AddField(
            model_name="facility",
            name="sig_unique_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Reference ID from the legacy HFR system",
                max_length=50,
                verbose_name="legacy unique ID",
            ),
        ),
        migrations.AlterField(
            model_name="facility",
            name="facility_type",
            field=models.CharField(
                choices=[
                    ("hospital", "Hospital"),
                    ("clinic", "Clinic"),
                    ("pharmacy", "Pharmacy"),
                    ("laboratory", "Laboratory"),
                    ("diagnostic", "Diagnostic Center"),
                    ("maternity", "Maternity Home"),
                    ("dental", "Dental Clinic"),
                    ("eye", "Eye Clinic"),
                    ("physiotherapy", "Physiotherapy Center"),
                    ("sarcs", "Sexual Assault Referral Centre"),
                    ("other", "Other"),
                ],
                db_index=True,
                max_length=50,
                verbose_name="facility type",
            ),
        ),
    ]
