# Generated by Django 5.0.1 on 2026-06-09 05:51

import apps.facilities.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0007_add_sig_unique_id_and_sarcs_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="facilityimage",
            options={},
        ),
        migrations.AlterField(
            model_name="facilityimage",
            name="image",
            field=models.ImageField(
                storage=apps.facilities.models.get_facilities_storage,
                upload_to="%Y/%m/%d/",
                verbose_name="image",
            ),
        ),
    ]
