# Generated by Django 5.0.1 on 2026-06-25 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0008_alter_facilityimage_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="facility",
            name="has_gbv_services",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Does this facility offer Gender Based Violence support services?",
                verbose_name="has GBV services",
            ),
        ),
        migrations.AlterField(
            model_name="facility",
            name="facility_type",
            field=models.CharField(
                choices=[
                    ("hospital", "Hospital"),
                    ("clinic", "Clinic"),
                    ("pharmacy", "Pharmacy"),
                    ("laboratory", "Laboratory"),
                    ("diagnostic", "Diagnostic Center"),
                    ("maternity", "Maternity Home"),
                    ("dental", "Dental Clinic"),
                    ("eye", "Eye Clinic"),
                    ("physiotherapy", "Physiotherapy Center"),
                    ("sarcs", "Sexual Assault Referral Centre"),
                    ("ngo", "NGO / Civil Society Organisation"),
                    ("police", "Police / Security"),
                    ("legal_aid", "Legal Aid Centre"),
                    ("social_welfare", "Social Welfare Office"),
                    ("shelter", "Shelter / Refuge"),
                    ("phc", "Primary Health Centre"),
                    ("other", "Other"),
                ],
                db_index=True,
                max_length=50,
                verbose_name="facility type",
            ),
        ),
        migrations.CreateModel(
            name="GBVServiceProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_types",
                    models.JSONField(
                        default=list,
                        help_text="List of GBV service type codes offered",
                        verbose_name="service types",
                    ),
                ),
                (
                    "target_group",
                    models.CharField(
                        choices=[
                            ("adults_and_children", "Adults and Children"),
                            ("adults_only", "Adults Only (18 and Over)"),
                            ("children_only", "Children Only (Under 18)"),
                        ],
                        default="adults_and_children",
                        max_length=50,
                        verbose_name="target group",
                    ),
                ),
                (
                    "organisation_type",
                    models.CharField(
                        choices=[
                            ("governmental", "Governmental"),
                            ("national_ngo", "National NGO"),
                            ("international_ngo", "International NGO"),
                            ("community_based", "Community-Based Organization"),
                            ("faith_based", "Faith-Based Organization"),
                            ("private", "Private"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="governmental",
                        max_length=50,
                        verbose_name="organisation type",
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="contact person"
                    ),
                ),
                (
                    "accessibility_info",
                    models.TextField(
                        blank=True,
                        help_text="Wheelchair access, sign language, ramps etc",
                        verbose_name="accessibility info",
                    ),
                ),
                (
                    "services_detail",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of specific services offered",
                        verbose_name="services detail",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "facility",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gbv_profile",
                        to="facilities.facility",
                    ),
                ),
            ],
            options={
                "verbose_name": "GBV service profile",
                "verbose_name_plural": "GBV service profiles",
                "indexes": [
                    models.Index(
                        fields=["organisation_type"],
                        name="facilities__organis_7d3f81_idx",
                    ),
                    models.Index(
                        fields=["target_group"], name="facilities__target__9cd3a2_idx"
                    ),
                ],
            },
        ),
    ]
