# Generated by Django 5.0.1 on 2026-06-26 05:21

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0009_facility_has_gbv_services_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facility",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True,
                geography=True,
                help_text="Geospatial coordinates (longitude, latitude)",
                null=True,
                srid=4326,
                verbose_name="location",
            ),
        ),
    ]
