# Generated by Django 5.0.1 on 2026-07-09 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0008_facilitybookmark_facilityviewhistory"),
        ("facilities", "0010_allow_null_location"),
    ]

    operations = []
