# Generated by Django 5.0.1 on 2026-08-13 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0011_merge_20260709_1342"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=96, unique=True, verbose_name="service name"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("clinical", "Clinical"),
                            ("diagnostics", "Diagnostics"),
                            ("pharmacy", "Pharmacy"),
                            ("gbv", "GBV"),
                            ("legal", "Legal"),
                            ("security", "Security"),
                            ("specialised", "Specialised"),
                            ("support", "Support"),
                        ],
                        db_index=True,
                        max_length=32,
                        verbose_name="category",
                    ),
                ),
                (
                    "hfr_service_id",
                    models.IntegerField(
                        blank=True,
                        help_text="service_id from the national HFR services table",
                        null=True,
                        unique=True,
                        verbose_name="HFR service ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "service",
                "verbose_name_plural": "services",
                "ordering": ["category", "name"],
            },
        ),
        migrations.AddField(
            model_name="facility",
            name="services_offered",
            field=models.ManyToManyField(
                blank=True,
                help_text="Structured services this facility provides (HFR taxonomy)",
                related_name="facilities",
                to="facilities.service",
            ),
        ),
    ]
