# Generated by Django 5.0.1 on 2026-09-08 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0012_service_facility_services_offered"),
    ]

    operations = [
        migrations.AddField(
            model_name="facility",
            name="availability",
            field=models.CharField(
                blank=True,
                help_text="Reported availability status (e.g. 24 hours, weekdays)",
                max_length=100,
                verbose_name="availability",
            ),
        ),
        migrations.AddField(
            model_name="facility",
            name="cost",
            field=models.CharField(
                blank=True,
                help_text="Reported cost tier or fee information",
                max_length=100,
                verbose_name="cost",
            ),
        ),
        migrations.AddField(
            model_name="facility",
            name="license_status",
            field=models.CharField(
                blank=True,
                help_text="Facility license/registration status from source registry",
                max_length=100,
                verbose_name="license status",
            ),
        ),
        migrations.AddField(
            model_name="facility",
            name="nhia_accepted",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Does this facility accept NHIA (national health insurance)?",
                verbose_name="NHIA accredited",
            ),
        ),
        migrations.AddField(
            model_name="facility",
            name="nhia_code",
            field=models.CharField(
                blank=True,
                help_text="NHIA accreditation code(s), semicolon-separated if multiple",
                max_length=255,
                verbose_name="NHIA code",
            ),
        ),
        migrations.AddField(
            model_name="facility",
            name="ward",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Ward — sub-LGA administrative area",
                max_length=150,
                verbose_name="ward",
            ),
        ),
    ]
