# Generated by Django 5.0.1 on 2026-03-23 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("facilities", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="reports/%Y/%m/%d/", verbose_name="image"
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="caption"
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="uploaded at"),
                ),
            ],
            options={
                "verbose_name": "report image",
                "verbose_name_plural": "report images",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="FacilityReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("fake", "Fake Facility"),
                            ("closed", "Permanently Closed"),
                            ("wrong_info", "Wrong Information"),
                            ("inappropriate", "Inappropriate Content"),
                            ("duplicate", "Duplicate Entry"),
                            ("spam", "Spam"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        verbose_name="reason",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed explanation of the issue",
                        verbose_name="description",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("investigating", "Under Investigation"),
                            ("resolved", "Resolved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal notes for admins",
                        verbose_name="admin notes",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="reported at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="resolved at"
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="facilities.facility",
                    ),
                ),
            ],
            options={
                "verbose_name": "facility report",
                "verbose_name_plural": "facility reports",
                "ordering": ["-created_at"],
            },
        ),
    ]
