# Generated by Django 5.0.1 on 2026-03-23 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("reports", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="facilityreport",
            name="reporter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="facility_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="reportimage",
            name="report",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="reports.facilityreport",
            ),
        ),
        migrations.AddIndex(
            model_name="facilityreport",
            index=models.Index(
                fields=["status", "-created_at"], name="reports_fac_status_902dc4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="facilityreport",
            index=models.Index(
                fields=["facility", "-created_at"],
                name="reports_fac_facilit_9510cb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="facilityreport",
            index=models.Index(
                fields=["reporter", "-created_at"],
                name="reports_fac_reporte_267ad8_idx",
            ),
        ),
    ]
