# Generated by Django 5.0.1 on 2026-06-09 05:51

import apps.reports.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportimage",
            name="image",
            field=models.ImageField(
                storage=apps.reports.models.get_reports_storage,
                upload_to="%Y/%m/%d/",
                verbose_name="image",
            ),
        ),
    ]
