# Generated by Django 5.0.1 on 2026-06-30 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0010_allow_null_location"),
        ("reports", "0003_alter_reportimage_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="facilityreport",
            name="address",
            field=models.CharField(blank=True, max_length=500, verbose_name="address"),
        ),
        migrations.AddField(
            model_name="facilityreport",
            name="city",
            field=models.CharField(blank=True, max_length=100, verbose_name="city"),
        ),
        migrations.AddField(
            model_name="facilityreport",
            name="facility_name",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="facility name"
            ),
        ),
        migrations.AddField(
            model_name="facilityreport",
            name="is_anonymous",
            field=models.BooleanField(
                default=False, verbose_name="reported anonymously"
            ),
        ),
        migrations.AddField(
            model_name="facilityreport",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="phone number"
            ),
        ),
        migrations.AddField(
            model_name="facilityreport",
            name="reasons",
            field=models.JSONField(blank=True, default=list, verbose_name="reasons"),
        ),
        migrations.AddField(
            model_name="facilityreport",
            name="state",
            field=models.CharField(blank=True, max_length=100, verbose_name="state"),
        ),
        migrations.AlterField(
            model_name="facilityreport",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Detailed explanation of the issue",
                verbose_name="description",
            ),
        ),
        migrations.AlterField(
            model_name="facilityreport",
            name="facility",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to="facilities.facility",
            ),
        ),
        migrations.AlterField(
            model_name="facilityreport",
            name="reason",
            field=models.CharField(
                choices=[
                    ("does_not_exist", "Facility Does Not Exist"),
                    ("wrong_info", "Wrong or Misleading Information"),
                    ("unsafe_conditions", "Poor and Unsafe Conditions"),
                    ("scam_fraud", "Scam or Fraud"),
                    ("unlicensed", "Unlicensed or Unauthorized"),
                    ("other", "Other"),
                ],
                max_length=20,
                verbose_name="reason",
            ),
        ),
    ]
